

subset(combine.table, is.na(combine.table$url))

fullcombine$url[1999] <- "https://www.sports-reference.com/cfb/players/trey-ragas-1.html"
fullcombine$url[986] <- "https://www.sports-reference.com/cfb/players/jeffery-wilson-2.html"
fullcombine$url[977] <- "https://www.sports-reference.com/cfb/players/mike-white-6.html"
fullcombine$url[975] <- "https://www.sports-reference.com/cfb/players/karaun-white-1.html"
fullcombine$url[967] <- "https://www.sports-reference.com/cfb/players/chris-warren-iii-1.html"
fullcombine$url[952] <- "https://www.sports-reference.com/cfb/players/kevin-toliver-ii-1.html"
fullcombine$url[949] <- "https://www.sports-reference.com/cfb/players/roc-thomas-1.html"
fullcombine$url[927] <- "https://www.sports-reference.com/cfb/players/trequan-smith-1.html"
fullcombine$url[909] <- "https://www.sports-reference.com/cfb/players/javon-rolland-jones-1.html"
fullcombine$url[904] <- "https://www.sports-reference.com/cfb/players/demario-richard-1.html"
fullcombine$url[865] <- "https://www.sports-reference.com/cfb/players/jmon-moore-2.html"
fullcombine$url[859] <- "https://www.sports-reference.com/cfb/players/kahlil-mckenzie-1.html"
fullcombine$url[858] <- "https://www.sports-reference.com/cfb/players/rj-mcintosh-1.html"
fullcombine$url[850] <- "https://www.sports-reference.com/cfb/players/tavares-martin-jr-1.html"
fullcombine$url[814] <- "https://www.sports-reference.com/cfb/players/richie-james-1.html"
fullcombine$url[805] <- "https://www.sports-reference.com/cfb/players/darius-jackson-1.html"
fullcombine$url[800] <- "https://www.sports-reference.com/cfb/players/maurice-hurst-jr-1.html"
fullcombine$url[790] <- "https://www.sports-reference.com/cfb/players/christopher-herndon-iv-1.html"
fullcombine$url[779] <- "https://www.sports-reference.com/cfb/players/dashawn-hand-1.html"
fullcombine$url[703] <- "https://www.sports-reference.com/cfb/players/christian-campbell-1.html"
fullcombine$url[672] <- "https://www.sports-reference.com/cfb/players/dorance-armstrong-jr-1.html"
fullcombine$url[663] <- "https://www.sports-reference.com/cfb/players/olasunkanmi-adeniyi-1.html"
fullcombine$url[484] <- "https://www.sports-reference.com/cfb/players/isaiah-jones-2.html"
fullcombine$url[316] <- "https://www.sports-reference.com/cfb/players/carson-wentz-1.html"
fullcombine$url[260] <- "https://www.sports-reference.com/cfb/players/rashard-robinson-1.html"
fullcombine$url[31] <- "https://www.sports-reference.com/cfb/players/james-bradberry-1.html"